cpus: '4'						# number of vCPUs
ram: '16384'						# RAM size in MBs
disk1_size: '120'					# disk size in Gbs
ignition_file: '{{ install_dir }}/master.64'		# location of the ignition data for master nodes
initial_port_check: 6443				# this is the machine-config-server port
initial_port_check_timeout: 900				# maximum number of seconds waiting for the openshit API on of the master node
customvalues:
  - key: disk.EnableUUID
    value: "TRUE"
  - key: guestinfo.ignition.config.data
    value: "{{ ignition_data }}"
  - key: guestinfo.ignition.config.data.encoding
    value: base64
  - key: sched.cpu.latencySensitivity
    value: High

disks_specs:
  - size_gb:  '{{ disk1_size }}'
    type: thin
    datastore: "{{ datastores | random }}"
