#
# You need to change the following entries to reflect your environment
#
install_dir: /root/install/ins
coreos_ova_path: "{{ install_dir }}/rhcos-410.8.20190516.0-vmware.ova"	# location of the RH CoreOS OVA
rhcos_template_name: clh-rhcos						# name we give to the VM when we deploy the RH CoreOS OVA
template_folder: 'clhtemplate'						# Folder where we  store the RH coreOS template
datastores: ['Docker_CLH']						# where to store the VMs
cluster_name: clh							# Name of the K*S Cluster

vm_portgroup: clhVLAN							# portgroup that the VMS connect to
dhcp_scope: '10.15.152.202,10.15.152.254'				# We deploy a DHCP service on the vm_protgroup VLAN, here is the scope assigned to DHC
infra_ip: 10.15.152.4							# DNS node 
gateway: '10.15.152.1'							# gateway on the vm_portgroup subnet 
domain_name: hpecloud.org						# 
resource_plane_vip: 10.15.152.5						# this is the IP of your load balancer
#
# You will not need to change the below
#
vcenter_hostname: vcentergen10.am2.cloudra.local
vcenter_username: Administrator@vsphere.local
vcenter_validate_certs: false
vcenter_cluster: Docker
datacenter: DEVOPS
ntp_servers: ['10.12.2.1']
dns_servers: ['10.10.173.1','10.10.173.31']

