#
# You need to change the following entries to reflect your environment
#
install_dir: /root/install/ins
coreos_ova_path: "/root/rhcos-410.8.20190516.0-vmware.ova"		# location of the RH CoreOS OVA
infra_folder: 'clhinfra'						# Folder where we create non-OCP VMs and templates
template: clh-rhcos							# VMWare Template to use when provisioning OCP machines
datastores: ['Docker_CLH']						# where to store the VMs
cluster_name: clh							# Name of the K*S Cluster

vm_portgroup: clhVLAN							# portgroup that the VMS connect to
dhcp_scope: '10.15.152.201 10.15.152.254'				# We deploy a DHCP service on the vm_protgroup VLAN, here is the scope assigned to DHC
dhcp_subnet: 10.15.152.0/24						# subnet to use by DHCP
gateway: '10.15.152.1'							# gateway on the vm_portgroup subnet 
domain_name: hpecloud.org						# 
resource_plane_vip: 10.15.152.5						# this is the IP of your load balancer
#
# You will not need to change the below
#
vcenter_hostname: vcentergen10.am2.cloudra.local
vcenter_username: Administrator@vsphere.local
vcenter_validate_certs: false
vcenter_cluster: Docker
datacenter: DEVOPS
ntp_servers: ['10.12.2.1']
dns_servers: ['10.10.173.1','10.10.173.31']

#
# temporary settings
#
external_lb_vip: "{{ hostvars[groups.loadbalancer.0].ip_addr }}"	# no vip implemented yet
internal_lb_vip: "{{ hostvars[groups.loadbalancer.0].ip_addr }}"	# no vip implemented yet
web_server_ip: 10.15.152.7						# IP of server with the bootstrap.ign file
