###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
- hosts: ocp
  name: Delete OCP VMs
  gather_facts: false
  connection: local

  tasks:
    - name: Power off VMs
      delegate_to: localhost
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        esxi_hostname: "{{ esxi_host }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ datacenter }}/vm/{{ cluster_name }}"
        name: "{{ inventory_hostname }}"
        state: poweredoff
      failed_when: false

    - name: Delete VMs
      delegate_to: localhost
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        esxi_hostname: "{{ esxi_host }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ datacenter }}/vm/{{ cluster_name }}"
        name: "{{ inventory_hostname }}"
        state: absent
      vars:
        ansible_connection: local

# voluntarily neutralized
- hosts: localhost:!localhost
  name: Delete Template

  tasks:
    - name: Delete RH CoreOS template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ datacenter }}/vm/{{ infra_folder }}"
        name: "{{ template }}"
        state: absent
      vars:
        ansible_connection: local

- hosts: infrastructure:loadbalancer
  name: Delete Infrastructure nodes
  gather_facts: no

  tasks:
    - name: Power off Infra VMs
      delegate_to: localhost
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ datacenter }}/vm/{{ cluster_name }}"
        name: "{{ inventory_hostname }}"
        state: poweredoff
      failed_when: false

    - name: Delete Infrastructure Node
      delegate_to: localhost
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ datacenter }}/vm/{{ infra_folder }}"
        name: "{{ inventory_hostname  }}"
        state: absent

